# Generated by Django 2.1.7 on 2019-03-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190318_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default_avatar.jpg', upload_to='avatars'),
        ),
    ]
